packages:
  - playground
catalog:
  '@antfu/eslint-config': ^4.10.1
  '@antfu/ni': ^24.1.0
  '@antfu/utils': ^9.1.0
  '@modelcontextprotocol/inspector': ^0.6.0
  '@modelcontextprotocol/sdk': ^1.7.0
  '@types/debug': ^4.1.12
  '@types/node': latest
  '@vitejs/plugin-vue': ^5.1.2
  '@vue/devtools-core': ^7.7.2
  '@vue/devtools-kit': ^7.7.2
  ansis: ^3.17.0
  birpc: ^2.2.0
  bumpp: ^10.1.0
  debug: ^4.4.0
  eslint: ^9.22.0
  hookable: ^5.5.3
  nanoid: ^5.1.3
  pathe: ^2.0.3
  tsx: ^4.19.3
  typescript: ~5.8.2
  unbuild: ^3.5.0
  vite: ^6.2.1
  vite-dev-rpc: ^1.0.7
  vite-hot-client: ^2.0.4
  vite-plugin-vue-mcp: ^0.0.0
  vue: ^3.4.37
  zod: ^3.24.2
catalogs:
  conflicts_vite-plugin-vue-mcp_catalog:
    vite-plugin-vue-mcp: catalog
  conflicts_vite-plugin-vue-mcp_catalo:
    vite-plugin-vue-mcp: catalo
  conflicts_vite-plugin-vue-mcp_catal:
    vite-plugin-vue-mcp: catal
  conflicts_vite-plugin-vue-mcp_cata:
    vite-plugin-vue-mcp: cata
  conflicts_vite-plugin-vue-mcp_cat:
    vite-plugin-vue-mcp: cat
  conflicts_vite-plugin-vue-mcp_ca:
    vite-plugin-vue-mcp: ca
  conflicts_vite-plugin-vue-mcp_c:
    vite-plugin-vue-mcp: c
  conflicts_vite-plugin-vue-mcp_:
    vite-plugin-vue-mcp: ''
  conflicts_vite-plugin-vue-mcp_w:
    vite-plugin-vue-mcp: w
  conflicts_vite-plugin-vue-mcp_wo:
    vite-plugin-vue-mcp: wo
  conflicts_vite-plugin-vue-mcp_wor:
    vite-plugin-vue-mcp: wor
  conflicts_vite-plugin-vue-mcp_work:
    vite-plugin-vue-mcp: work
